### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by meiyasan** [scheb/2fa#114]
Hello @scheb !

Any plan to make SF6 compatibility ?
I would be happy to contribute if needed

**Comment by scheb** [comment]
See #62, though didn't find the time and motivation yet to push that through. If you want to live on the edge, you can reference the `6.x` branch which is already compatible and fully working with Sf6. But be warned, it's a development branch and I'm messing around with it quite a lot. So better refer to a specific (stable) commit, rather than taking the latest one.
