### ISSUE TITLE
User Deprecated, implement isAuthenticated

### ISSUE THREAD

**Issue by PhilETaylor** [scheb/2fa#117]
**Bundle version**: 5.13.x
**Symfony version**: 5.4.x
**PHP version**: 8.1.x
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

Just a simple User Deprecated message to resolve :) 
```
2021-12-17T09:10:09+00:00 [info] User Deprecated: Class "Scheb\TwoFactorBundle\Security\Authentication\AuthenticationTrustResolver" should implement method "Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolverInterface::isAuthenticated(TokenInterface $token = null): bool".
```

**To Reproduce**

`php bin/console cache:clear`

<img width="1613" alt="Screenshot 2021-12-17 at 09 13 15" src="https://user-images.githubusercontent.com/400092/146519590-8f9682ce-9105-4b8c-b5df-1fef33161d76.png">

**Comment by PhilETaylor** [comment]
Im confused though, as `Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolverInterface` has no method `isAuthenticated` !?!?!

edit: ah found this:

```
    /**
     * Resolves whether the passed token implementation is authenticated
     * anonymously.
     *
     * If null is passed, the method must return false.
     *
     * @return bool
     *
     * @deprecated since Symfony 5.4, use !isAuthenticated() instead
     */
    public function isAnonymous(TokenInterface $token = null);
```

**Comment by scheb** [comment]
`isAuthenticated` is a required method in Symfony 6, in Symfony 5.4 it's optional. Not implementing it is causing a deprecation notice. That's why it is annotated as a method via PHPDoc and not as an actual method in the interface, so it doesn't break code that hasn't implememented the method yet.

Overall, not a critical issue, but I see that it's annoying seeing that deprecation notice all the time. I can backport that Symfony 6 compatibility change to the 5.x branch later, so that the deprecation notice goes away. Not a bug though, since the system is still working fine without it.

**Comment by PhilETaylor** [comment]
totally... no pressure from me, I only logged it as a note rather than a bug to be fixed :) this could even be closed as long as you are aware

**Comment by scheb** [comment]
v5.13.1 addresses that.

**Comment by PhilETaylor** [comment]
Thanks for looking into this so soon. Appreciated greatly.

**Comment by scheb** [comment]
I'm disappointed, that you're not living on the edge as much as you'd normally do. `6.x-dev` is the way to go ;)

**Comment by PhilETaylor** [comment]
because not all my vendors are as responsible or reactive as you haha I normally end up having to fork a lot to jump the constrains in their composer.json 

I have Christmas to re-attempt it. 

Im running PHP 8.1.1 though ;-) so... almost on the edge :)
