### ISSUE TITLE
Allow users to have multiple secrets

### ISSUE THREAD

**Issue by sfavot** [scheb/2fa#124]
**Description**

Currently when using TOTP, the user will be expected to have a single secret. However, in some cases, we want to allow users to use multiple devices for codes generation. If I understand correctly how TOTP is intended to work, these users would then have multiple secrets: one per device.
Also if it was a deliberate choice of yours to allow only one secret per user, I'm curious as to know why?

**Comment by scheb** [comment]
That is unfortunately not possible in the standard implementation of the TOTP provider. There is no specific reason for it being a single secret, it's just always been like that and until now it has been sufficient. You're the first person asking for this :)

I'm not considering implementing this any time soon, since there hasn't been any demand and it'd be a backwards compatibility break (so no chance adding this in 6.x).

As a solution I'd suggest you implement your own [custom two-factor provider](https://symfony.com/bundles/SchebTwoFactorBundle/current/providers/custom.html), which can be basically a copy of the [standard TOTP implementation coming with the bundle](https://github.com/scheb/2fa-totp) and do the changes to support multiple secrets.

**Comment by sfavot** [comment]
Thanks, that's what I ended up doing. 👍
