### ISSUE TITLE
SMS Support

### ISSUE THREAD

**Issue by TheAFOGroup** [scheb/2fa#144]
**Description**

I may be wrong and this already might be supported, but unfortunately I cannot see it. Would it be possible to add support for 2FA via SMS? A service like https://www.twilio.com/sms or alternative?

Many thanks

**Comment by Spomky** [comment]
Hi @WebDevM4DC,

You are right; the SMS support is not part of this project.

@scheb, instead of having X notification methods here (email, SMS...), it could be interesting to leverage on the [`symfony/notifier` component](https://symfony.com/doc/current/notifier.html). With this component, we do not care of the notification method and subsequent providers.
WDYT?

**Comment by TheAFOGroup** [comment]
> Hi @WebDevM4DC,
> 
> You are right; the SMS support is not part of this project.
> 
> @scheb, instead of having X notification methods here (email, SMS...), it could be interesting to leverage on the [`symfony/notifier` component](https://symfony.com/doc/current/notifier.html). With this component, we do not care of the notification method and subsequent providers. WDYT?

Thanks, I believe having SMS is the most basic and crucial method to have. Others are more "advanced". The idea with notifier from symfony seems nice.

**Comment by scheb** [comment]
I'm not planning to add SMS support as a out-of-the-box solution, because there are too many different ways to send SMS and by [implementing a custom 2fa provider](https://symfony.com/bundles/SchebTwoFactorBundle/6.x/providers/custom.html) you can have any solution you want.

For SMS authentication, have a look at https://github.com/Erkens/2fa-text, which is providing the "glue" part and just needs you to implement the SMS sending.

notifier component looks interesting, but same here: if you want to use it, a custom 2fa provider is the way to go.

**Comment by TheAFOGroup** [comment]
> I'm not planning to add SMS support as a out-of-the-box solution, because there are too many different ways to send SMS and by [implementing a custom 2fa provider](https://symfony.com/bundles/SchebTwoFactorBundle/6.x/providers/custom.html) you can have any solution you want.
> 
> For SMS authentication, have a look at https://github.com/Erkens/2fa-text, which is providing the "glue" part and just needs you to implement the SMS sending.
> 
> notifier component looks interesting, but same here: if you want to use it, a custom 2fa provider is the way to go.

Thank you, this is extremely helpful!
