### ISSUE TITLE
endroid/qr-code v4 support

### ISSUE THREAD

**Issue by sdespont** [scheb/2fa#151]
**Description**

Any reason to not supporting https://github.com/endroid/qr-code v4 for https://github.com/scheb/2fa-qr-code ?

I am asking because the v3.* rise deprecated warnings.

**Comment by scheb** [comment]
I was looking into this a while ago. As far as I remember, the API changed a lot with v4 and would have been too much of a hassle to support both versions in the same package. And with bundle version 6, I eventually decided to discontinue the 2fa-qr-code package entirely, because it doesn't really do much except the glue code between bundle and QR code rendering library.

My recommendation: Remove the qr-code bundle and implement the QR code rendering part yourself. It's just a bit more code and that's what I'm doing as well with bundle version 6. An example how to render with endroid/qr-code v4 can be found here: https://github.com/scheb/2fa/blob/6.x/app/src/Controller/QrCodeController.php

**Comment by sdespont** [comment]
@scheb OK, thank you for the advice
