### ISSUE TITLE
lcobucci/jwt 4.2.0 b/c break - Key provided is shorter than 256 bits, only 240 bits provided

### ISSUE THREAD

**Issue by PhilETaylor** [scheb/2fa#157]
**Bundle version**: 6.2.0
**Symfony version**: 6.1
**PHP version**: 8.1
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

lcobucci/jwt 4.2.0 has a b/c break (on purpose) which has resulted in exceptions

composer why lcobucci/jwt says scheb/2fa

`Lcobucci\JWT\Signer\InvalidKeyProvided: Key provided is shorter than 256 bits, only 240 bits provided`

Full stack trace https://sentry.io/share/issue/dc48c4847b5e4be68a51d69354cb5383/

**To Reproduce**

Its sporadic and DOESN'T happen on every login or use of 2fa. 

Its after login, but no idea yet anything other than the stack trace, we have been using scheb/2fa (and its previous versions) for many many years so some users might have very old setup of 2fa. 

It doesn't affect all users. Also if I set up a new 2fa on an account, I can login with no issues. Which is why I mention about "old setups". Also using 6 digit codes for full Google Authenticator compatibility in this app. 

Its on the post to /2fa_check with what appears to be a valid generated code supplied by the user

<img width="394" alt="Screen Shot 2022-08-21 at 12 21 38" src="https://user-images.githubusercontent.com/400092/185788568-7d7ee18c-5bae-4593-aa42-3b15c7e6c6da.png">

For now downgrading to `lcobucci/jwt: 4.1.5` seems to be enough to silence this - so that we can all enjoy our Sunday :) 

**Additional Context**

Release Notes https://github.com/lcobucci/jwt/releases/tag/4.2.0

Documentation on deprecation https://lcobucci-jwt.readthedocs.io/en/4.2.0/supported-algorithms/

**Comment by lcobucci** [comment]
You may use the deprecated implementations that don't validate the key length (at least until you're able to rotate the keys)

**Comment by PhilETaylor** [comment]
> You may use the deprecated implementations that don't validate the key length (at least until you're able to rotate the keys)

Yup - absolutely no rush here :-) 

> For now downgrading to lcobucci/jwt: 4.1.5 seems to be enough to silence this - so that we can all enjoy our Sunday :)

**Comment by lcobucci** [comment]
I've sent a PR that should provide flexibility to users to: choose for an algorithm implementation that doesn't validate the key length (v4.2+ only) or change the key only for JWT generation (be mindful that validation will use the new key).

I hope it helps :+1:

**Comment by PhilETaylor** [comment]
The ideal world would be:

- lcobucci/jwt 4.2+
 - New set up of 2fa by a user uses the key that is long and passes lcobucci/jwt 4.2+ validation and is the future (and the way scheb/2fa has done for a while now - I have 1000s of these) 
 - Old users with a 16 char totp secret (I have over 100 of these!) to still be able to validate their totp digits and then to throw the exception saying it needs rotating AFTER its been validated as a valid TOTP so we can provide an interface for the user to scan a new secret to their device (1Password,GoogleAuthenticator) and then save that to our db.

Again, absolutely no rush, the solution for the weekend is to pin lcobucci/jwt on 4.1.x and everything works as it should. But of course a longer term solution to the b/c break for scheb/2fa implementations that have very old users set up with totp secrets that are 16 char in length.

to be clear, the ONLY affected scheb/2fa users are those that have users that set up 2fa many many years ago - because setting up a new 2fa with scheb/2fa today WORKS with lcobucci/jwt on 4.2.x - its only the old users that cause the Exception.

Hope this helps understanding.

**Comment by yakobe** [comment]
Hi there.

I'm having a very similar problem to this with the error:
>Key provided is shorter than 256 bits, only 200 bits provided

I have also pinned to [v4.1.5](https://github.com/lcobucci/jwt/releases/tag/4.1.5) for now. However, i cannot seem to identify what needs to be updated. I had a look at https://github.com/scheb/2fa/pull/158 but don't really get what i will have to change. What is causing the issue? Is it that the private/public keys are not secure enough? Or is there something internal to this package that needs updating?

@PhilETaylor I ask because you say that newly configured trusted devices work for you, but I always seem to get the error 😅.

Any guidance as to what i am doing wrong would be greatly appreciated. An thanks for all this great work 👍

**Comment by lcobucci** [comment]
@yakobe the only explanation I have for @PhilETaylor's varying behaviour is a varying [`kernel.secret`](https://symfony.com/doc/current/reference/configuration/framework.html#secret) (which makes no sense to me, honestly).

The issue here is the following: JWT RFCs define minimum key length (depending on the algorithm). This lib uses HS256 which, according to the RFC, requires at least 32 bytes (256 bits) long keys. 

Until 4.2.0 of the underlying library the requirement wasn't enforced. We deemed that a security bug and decided to ship a behavioural BC-break. Highlighting the lack of compliance (and possible lack of security) in different apps.

What #158 does is provide options to end-users. They can choose to:

1. override only the key for token creation/validation - moving away from `kernel.secret` and containing the potential damage of key rotation
1. override only the algorithm used for token creation/validation - allowing users to (temporarily) accept the potential security implications and bypass key length requirements
1. (bonus) override the whole configuration object - allowing people completely own lcobucci/jwt setup and decide to mitigate the issue by themselves

**Comment by yakobe** [comment]
@lcobucci thanks for the clarification about the pull request and for making this safer by forcing minimum security standards. I agree that security trumps compatibility :) 

I'm still a little confused if there are any changes I can do to allow the installation of 4.2.0? Do i need to generate a better key pair, or change some sort of setting? Or are the changes required in this repository and I just need to use 4.1.5 for now.

**Comment by lcobucci** [comment]
@yakobe changing the `kernel.secret` to have a longer string would suffice but since it is also used by symfony you may have unintended consequences on your app.

**Comment by yakobe** [comment]
@lcobucci i think i worked it out just as your message arrived 😆. I didn't realize that it was using `kernal.secret` as the passphrase for the trusted devices JWT (since there is other JWT configuration in the app with the error).

Sorry, and many thanks!

**Comment by scheb** [comment]
[v6.3.0](https://github.com/scheb/2fa/releases/tag/v6.3.0) released with a new configuration option, to configure a encryption key of sufficient length, without needing to change the `kernel.secret`.

**Comment by PhilETaylor** [comment]
Amazing. I'll take it for a test drive over the weekend if you dont mind waiting a little for my feedback on that. Thanks again and sorry to disturb your vacation/holiday.

**Comment by PhilETaylor** [comment]
I took some time out to fully get to the bottom of understanding this today, made the changes (`scheb_two_factor.trusted_device.key` set to something much longer than my "too short" `kernel.secret`) to my live app, and upgraded all libs again, and Im pleased to report no more issues.

Ive just deployed to production, but im not expecting any issues there either. 

Many thanks both of you for your outstanding contributions and work - Ill close this issue now.

**Comment by jkabat** [comment]
@PhilETaylor what if I do not have trusted device section enabled?

I still see the error, but I have no possibility to override - have I?

EDIT: it turned out that error comes from another consumer of JWT library. You can ignore this message.
