### ISSUE TITLE
Trusted devices JWTs are issued in the future

### ISSUE THREAD

**Issue by BastienClement** [scheb/2fa#163]
**Bundle version**: 6.3.0
**Symfony version**: 5.4
**PHP version**: 8.0.16
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

Since we updated scheb/2fa-* to the latest version, we started observing random failures in our functional testing suite.

The test procedure is the following:
1. Login to the website
2. Assert we are asked to provide 2fa auth
3. Enable trusted device and login
4. Logout and login again
5. Assert we are not prompted for 2fa again

But randomly, this test would fail with a new 2fa prompt at step 5 despite the trusted device feature being enabled.

---

Below are some dumps from `vendor/lcobucci/jwt/src/Validation/Validator.php` showing what the issue is.

The current time (`dump(new DateTime())`)
```
^ DateTime @1663968082 {#10272
  date: 2022-09-23 21:21:22.781551 UTC (+00:00)
}
```

The JWT being validated
```
^ Lcobucci\JWT\Token\Plain^ {#6784
  ...
  -claims: Lcobucci\JWT\Token\DataSet^ {#347
    -data: array:5 [
      "iat" => DateTimeImmutable @1663968083 {#336
        date: 2022-09-23 21:21:23.0 +00:00
      }
      ...
```

The validation error
```
^ Lcobucci\JWT\Validation\ConstraintViolation^ {#480
  +constraint: "Lcobucci\JWT\Validation\Constraint\LooseValidAt"
  #message: "The token was issued in the future"
  #code: 0
  #file: "./vendor/lcobucci/jwt/src/Validation/ConstraintViolation.php"
  #line: 21
  ...
```

Obviously, the time is being rounded up when serialized in the JWT. This is an issue in CI environment as the subsequent login attempt will be made without delay.

**Additional Context**

Since the bundle does not seem to offer a way to configure the leeway time for token validation, we worked around the issue by applying a patch to the JWT Encoder and subtracting a whole second from the "issuedAt" time. We believe this should be an issue fixed either in this bundle, or in the `lcobucci\jwt` dependency.

```patch
diff --git a/Security/TwoFactor/Trusted/JwtTokenEncoder.php b/Security/TwoFactor/Trusted/JwtTokenEncoder.php
index b4dc38b..f4eaad8 100644
--- a/Security/TwoFactor/Trusted/JwtTokenEncoder.php
+++ b/Security/TwoFactor/Trusted/JwtTokenEncoder.php
@@ -33,7 +33,7 @@ class JwtTokenEncoder
     public function generateToken(string $username, string $firewallName, int $version, DateTimeImmutable $validUntil): Plain
     {
         $builder = $this->configuration->builder()
-            ->issuedAt($this->clock->now())
+            ->issuedAt($this->clock->now()->sub(new \DateInterval('PT1S')))
             ->expiresAt($validUntil)
             ->withClaim(self::CLAIM_USERNAME, $username)
             ->withClaim(self::CLAIM_FIREWALL, $firewallName)
```

**Comment by scheb** [comment]
It's behavior of either `lcobucci\jwt` or `lcobucci\clock`, so I'd recommend you report the problem to the respective libraries.

I personally can't reproduce this behavior in my test setup. For me, the `"iat" => DateTimeImmutable` value isn't rounded up, it's deserialized with the precise second fraction:


```
  object(Lcobucci\JWT\Token\DataSet)#495 (2) {
    ["data":"Lcobucci\JWT\Token\DataSet":private]=>
    array(5) {
      ["iat"]=>
      object(DateTimeImmutable)#496 (3) {
        ["date"]=>
        string(26) "2022-09-25 10:09:29.487615"
```

Here's my dependencies, maybe your versions are significantly different, that would give you a pointer:

```
lcobucci/clock                     2.2.0   Yet another clock abstraction
lcobucci/jwt                       4.2.1   A simple library to work with JSON Web Token and JSON Web Signature
```

---

In regards to the test cases, you actually want to remove the passing of time from your tests as an uncontrollable factor. That's why the `lcobucci\jwt` library is using `lcobucci\clock` as a time provider. Per default, the system time is used, though within test cases you want to replace the clock with a test object that returns time according to your needs.

For that purpose, the `JwtTokenEncoder` lets you inject a clock object:
https://github.com/scheb/2fa/blob/2b77bf99c0ca80e9dd80e6f32eaa041e96ce6704/src/trusted-device/Security/TwoFactor/Trusted/JwtTokenEncoder.php#L28

So for your test cases, you extend the DIC configuration to pass in a clock object which is under control of your test case. You return a static time value and only change that time value when you want to "pass time" within our test case. That way your test cases become deterministic and stable.

**Comment by scheb** [comment]
Closed, because not reproducible.
