### ISSUE TITLE
enable_authenticator_manager deprecated by symfony

### ISSUE THREAD

**Issue by AbdullahAlhariri** [scheb/2fa#183]
**Bundle version**: 6.6.0
**Symfony version**: 6.2
**PHP version**: 8.1.13
**Using authenticators** (`enable_authenticator_manager: true`): NO

**Description**
When setting enable_authenticator_manager to true, as mentioned in the [upgrade guide (5.x to 6.x)](https://github.com/scheb/2fa/blob/6.x/UPGRADE.md).
I get a deprecation from symfony telling me that enable_authenticator_manager has been deprecated
`Since symfony/security-bundle 6.2: The "enable_authenticator_manager" option at "security" is deprecated.`

Have you looked into this before? 

**To Reproduce**

1. Make sure you are running symfony 6.2 with php 8.1
2. In `security.yaml` set `enable_authenticator_manager: true`
3. Then see deprecation in symfony profiler > logs > deprecations

**Comment by scheb** [comment]
Looks like Symfony deprecated this option with Symfony 6.2, so you're no longer required to set it. So don't set it and you'd be fine.

**Comment by AbdullahAlhariri** [comment]
Okay sure, Will this get removed from the upgrade guide?
If so I would like to contribute!

**Comment by scheb** [comment]
It still needs to be mentioned in the upgrade instructions, because it's relevant for people upgrading to bundle version 6 on Symfony 5.4.

Turns out setting the `enable_authenticator_manager: true` option is no longer required since Symfony 6.0.2 (https://github.com/symfony/symfony/pull/44554). Added a note in the upgrade instructions.
