### ISSUE TITLE
Custom prepare trigger to enable selection of 2FA method at login

### ISSUE THREAD

**Issue by alexbaileyuk** [scheb/2fa#205]
I've spent a few days trying to find a solution to support a flow such as this:

1. User logs in using JSON login option.
2. User is put in intermediate state `IS_AUTHENTICATED_2FA_IN_PROGRESS`.
3. User selects one of multiple 2fa methods in the UI.
4. Selected 2FA method is triggered via JSON POST call.
5. User enters code and verifies via JSON POST request.

I can see a few options available for this (`prepare_on_login` and `prepare_on_access_denied`) but they are perhaps not flexible enough.

Currently the only really viable option is that the user gets an email (or some other 2FA is prepared and process begun) as soon as the login page is hit. This means that the user doesn't get chance to select the option they want to use if they have multiple set up.

The reason I have this requirement is because by default, all of the app users have email enabled. The application wants to offer two other forms of authentication (TOTP and custom) for the user to select from.

Originally I thought I could just add a POST endpoint with access control set to `IS_AUTHENTICATED_2FA_IN_PROGRESS` so I could inject some service to trigger the selected 2FA method. However, I can't find a service for that (seems to all happen in `TwoFactorProviderPreparationListener`) so I don't think it's possible.

I feel like if the logic from `TwoFactorProviderPreparationListener::onKernelResponse` was abstracted out into some other injectable service which took a user and 2FA provider alias then this would be possible.

What do you think? I'd be happy to make an attempt at creating a PR if it's something that sounds feasible or sensible?

**Comment by scheb** [comment]
Have you seen this -> https://symfony.com/bundles/SchebTwoFactorBundle/current/multi_authentication.html

Implementing `Scheb\TwoFactorBundle\Model\PreferredProviderInterface` on your user entity lets the user define a default authentication provider. This could be an option in your user settings.

Besides that, the 2fa authentication method to be used can be determined with the `preferTwoFactorProvider()` method on the `TwoFactorToken` security token. There's the implementation in the controller: https://github.com/scheb/2fa/blob/5bd6698f9c006f3a7384eee0dc67b1e1fa7089e5/src/bundle/Controller/FormController.php#L59C5-L71

Since you're having a JSON API on the backend, rather than using the controller, you could implement an extra API endpoint to switch the 2fa authentication provider on the security token (the way it's shown in the controller) and trigger the 2fa preparation process. Then the security code posted from the UI will be evaluated by that newly chosen authentication provider.
