### ISSUE TITLE
Pass TwoFactorTokenInterface to PreferredProviderInterface

### ISSUE THREAD

**Issue by danielburger1337** [scheb/2fa#212]
It would be helpful to pass the current token context to the `PreferredProviderInterface::getPreferredTwoFactorProvider()` method so that we can make decisions on what provider should be preferred when the preferred one is unavailable.

My use case is that I have a custom passkey provider and I also allow users to sign in with a passkey. Through a token attribute which I check in my TwoFactorProvider, I disable passkey support for users that originally authenticated with the passkey.

When `passkey` is the users preferred two factor provider and now the provider is blocked, the default provider order is used. 

This is kinda suboptimal because "email" is before "totp" and will send an email on request. It would be better to then fallback to the TOTP provider so that a potentially unnecessary email is not sent. 

An alternative would be to somehow allow to configure the order of providers, but that would require an extensive change to the codebase.

**Comment by scheb** [comment]
Can't just change this, because it's a breaking change.

In my opinion, the interface should stay as simple as possible, since it's meant to be implemented in the user entity and return the user's preference. It's not really meant to contain a lot of complex business code.

The better solution would probably be to extract this piece of code https://github.com/scheb/2fa/blob/7990826108680acb90ea308d8115c62fe2a0cbc6/src/bundle/Security/TwoFactor/Provider/TwoFactorProviderInitiator.php#L58-L75 into a service, which can be overwritten via config for the case when you'd need to inject your own custom logic.
