### ISSUE TITLE
Auto-enabling trusted_device when remember me is on

### ISSUE THREAD

**Issue by Seldaek** [scheb/2fa#66]
I am trying to keep the 2FA page as simple as possible and so would rather not add yet another checkbox people have to think about. I therefore figured I would enable the trusted_device flag when remember me is active, as that kind of has the same intent.

It seems `count($token->getAttribute('remember_me_cookie')) > 0` can be used to check for the remember me presence, but that is not accessible in the template, so can't easily be done without overriding the whole form controller. If this request sounds reasonable to you it'd be nice to expose this as a flag to the template perhaps?

**Comment by scheb** [comment]
Would be doable and I see the use-case. I could add a firewall option `remember_me_is_trusted_flag` (or something like that), which automatically activates the trusted flag whenever the remember-me option has been checked.

I'd like to wait with the implementation until Symfony 5.3 is released and I can finalize #61, because then the implementation for the authenticator system will become a bit easier.

Until then, I'd suggest as workaround you pass a variable to your form template, that tells you if the remember-me option was checked, then add a hidden field with the trusted flag. You have two options how to do that:

Option 1: Implement your own form renderer, pass an extra variable into the template, which is checking for `$currentToken->hasAttribute(TwoFactorTokenInterface::ATTRIBUTE_NAME_REMEMBER_ME_COOKIE)`. [This how-to](https://github.com/scheb/2fa/blob/5.x/doc/firewall_template.md) is not describing your use-case, but it shows how to implement such a form renderer.

Option 2: Extend [FormController](https://github.com/scheb/2fa/blob/5.x/src/bundle/Controller/FormController.php) and override the `getTemplateVars` method to add another template variable.

Would be a matter of taste which option you'd choose. Both achieve the same effect, an extra variable for the template. Option 2 is probably easier, because you already get the token passed in the method arguments.

A word of warning: Once #61 is merged and released and when you're using it with the authenticator system, that token attribute will no longer be there. There will likely be a different token attribute, in the current WIP state it is `const ATTRIBUTE_NAME_USE_REMEMBER_ME = 'use_remember_me'`. But potentially by that time I can deliver the proper solution to this problem, the one that I have described above.

**Comment by Seldaek** [comment]
Ok thanks for the hint, Option 2 sounds good for now. A new option in a future release sounds even better. I'm already subscribed to #61 and others, I definitely will keep a close eye on what happens here and to the new Authenticator stuff in Symfony as it is all experimental and we are going to deploy this soon on a fairly large audience I'd rather avoid surprises :)

**Comment by scheb** [comment]
Version 5.13.0 now has a `remember_me_sets_trusted` option on the firewall config.

**Comment by Seldaek** [comment]
Thanks :)
